spring-boot-plus:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 当前环境服务IP地址
  server-ip: 127.0.0.1
  # 文件上传下载配置
  upload-path: /opt/upload/


spring:
  datasource:
    url: jdbc:mysql://114.116.123.125:3306/materialdb20200424?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&&autoReconnect=true
    username: root
    password: Tech0827

  # Redis配置
  #redis:
  #  database: 0
  #  host: 39.98.129.45
  #  password:
  #  port: 6379

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl